### ISSUE TITLE
Could you supply an example?

### ISSUE THREAD

**Issue by 20v100** [bustlelabs/ember-content-kit#26]
Sorry for my ignorance but I do not understand how to use the most basic function of the {{content-kit-editor}}. How do I get and save the text I input in the editor? Could someone provide a quick example?

**Comment by rlivsey** [comment]
@20v100 the [demo app](bustlelabs.github.io/content-kit-editor/demo) for content-kit itself uses this addon, so that's worth a look through. The [source is here](https://github.com/bustlelabs/content-kit-editor/tree/master/demo).

Eg, [here you can see](https://github.com/bustlelabs/content-kit-editor/blob/master/demo/app/templates/index.hbs#L28-L35) how the editor is setup and the actions handled to get content when the user enters text:

```handlebars
{{#content-kit-editor
    class='post-editor__editor'
    mobiledoc=mobiledoc
    cards=(content-kit-cards-list)
    on-change=(action 'didEdit')
  as |contentKit|}}
  {{content-kit-toolbar contentKit=contentKit}}
{{/content-kit-editor}}
```

The main bit of interest there is `mobiledoc=mobiledoc` which is how you setup the initial value, and `on-change=(action 'didEdit')` so `didEdit` will get called with the updated mobiledoc when changes are made.

Hope that helps get you started.

**Comment by 20v100** [comment]
@rlivsey Thanks for the quick reply. I went through the demo and If I may hazard another question: Since the mobiledoc is composed of cards, why do I need to also pass 'cards=(content-kit-cards-list)' to the content-kit-editor?

**Comment by mixonic** [comment]
@20v100 the cards there are the card implementations. Mobiledocs store card payload data, but the actual implementation of a card (the JavaScript to render it) must be passed to the renderer (in this case, to the editor).

More about cards [here in CARDS.md](https://github.com/bustlelabs/content-kit-editor/blob/master/CARDS.md).

If your application has no cards, you don't need to pass any definitions.

**Comment by mixonic** [comment]
Closing this as @rlivsey is correct that the Content-Kit demo ([demo](http://bustlelabs.github.io/content-kit-editor/demo/) [source](https://github.com/bustlelabs/content-kit-editor/tree/master/demo)) is a full-blown example of using this addon. Additionally this repo has many tests that should serve to illustrate more cases.

But let me know if you have any other questions @20v100

**Comment by 20v100** [comment]
Thanks a lot for you help. Much appreciated. I should be able to figure it from here.
